# Generated by Django 3.2.5 on 2021-08-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionstep',
            old_name='desription',
            new_name='formula',
        ),
        migrations.RemoveField(
            model_name='solutionstep',
            name='formula_url',
        ),
        migrations.AddField(
            model_name='solutionstep',
            name='n',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutionstep',
            name='problem_id',
            field=models.TextField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
